name: Staging Deployment

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Staging Deploy
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: scfa-terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init (Staging)
        run: |
          terraform init \
            -backend-config="key=scfa/staging/terraform.tfstate"
  

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan (Staging)
        run: terraform plan -var-file="staging.tfvars"

      - name: Terraform Apply (Staging)
        run: terraform apply -auto-approve -var-file="staging.tfvars"

- name: Wait for service to stabilize
        run: sleep 30

      - name: Health Check
        run: |
          URL=$(terraform output -raw alb_dns_name)
          echo "Checking $URL"
          curl -f "http://$URL/health"

